// Reference generator: emits a Rust test file of golden vectors from the real
// upstream openqmc headers. Compiled with -DOQMC_FORCE_SCALAR so the values come
// from the scalar path (the same algorithm the Rust port implements).
#include <oqmc/latticebn.h>
#include <oqmc/lattice.h>
#include <oqmc/owen.h>
#include <oqmc/pcg.h>
#include <oqmc/pmjbn.h>
#include <oqmc/pmj.h>
#include <oqmc/rank1.h>
#include <oqmc/sobolbn.h>
#include <oqmc/sobol.h>
#include <oqmc/state.h>
#include <oqmc/stochastic.h>

#include <cstdint>
#include <cstdio>
#include <vector>

namespace {

void emit4(const char* fn, int x, int y, int frame, int index, int domain,
           const std::uint32_t out[4]) {
    std::printf("    %s(%d, %d, %d, %d, %d, [0x%08x, 0x%08x, 0x%08x, 0x%08x]);\n",
                fn, x, y, frame, index, domain, out[0], out[1], out[2], out[3]);
}

// (x, y, frame, index, domain) tuples exercising the full state machine.
struct Case { int x, y, frame, index, domain; };
std::vector<Case> cases() {
    std::vector<Case> c;
    for (int x : {0, 1, 2, 5, 200, 255, 256, 1000})
        for (int frame : {0, 1, 7})
            for (int index : {0, 1, 3, 42, 65535, 65536, 70000})
                for (int domain : {0, 1, 13})
                    c.push_back({x, x * 3 + 1, frame, index, domain});
    return c;
}

template <typename Sampler>
void emitSampler(const char* fn, const void* cache) {
    for (auto k : cases()) {
        const auto s = Sampler(k.x, k.y, k.frame, k.index, cache);
        const auto d = s.newDomain(k.domain);
        std::uint32_t out[4];
        d.template drawSample<4>(out);
        emit4(fn, k.x, k.y, k.frame, k.index, k.domain, out);
    }
}

} // namespace

int main() {
    std::printf("// AUTO-GENERATED by ref_gen.cpp from upstream openqmc. Do not edit.\n");
    std::printf("#![allow(clippy::all)]\n");
    std::printf("use openqmc::{SobolSampler, LatticeSampler, PmjSampler,\n");
    std::printf("    SobolBnSampler, LatticeBnSampler, PmjBnSampler};\n");
    std::printf("use openqmc::{owen, rank1, pcg, stochastic};\n");
    std::printf("use openqmc::state::State64Bit;\n\n");

    // Helper definitions (shared by the generated calls).
    std::printf(R"RUST(
fn ck_sobol(x: i32, y: i32, f: i32, i: i32, d: i32, e: [u32; 4]) {
    assert_eq!(SobolSampler::new(x, y, f, i).new_domain(d).draw_sample::<4>(), e,
        "sobol x{x} y{y} f{f} i{i} d{d}");
}
fn ck_lattice(x: i32, y: i32, f: i32, i: i32, d: i32, e: [u32; 4]) {
    assert_eq!(LatticeSampler::new(x, y, f, i).new_domain(d).draw_sample::<4>(), e,
        "lattice x{x} y{y} f{f} i{i} d{d}");
}
fn ck_pmj(x: i32, y: i32, f: i32, i: i32, d: i32, e: [u32; 4]) {
    assert_eq!(PmjSampler::new(x, y, f, i).new_domain(d).draw_sample::<4>(), e,
        "pmj x{x} y{y} f{f} i{i} d{d}");
}
fn ck_sobolbn(x: i32, y: i32, f: i32, i: i32, d: i32, e: [u32; 4]) {
    assert_eq!(SobolBnSampler::new(x, y, f, i).new_domain(d).draw_sample::<4>(), e,
        "sobolbn x{x} y{y} f{f} i{i} d{d}");
}
fn ck_latticebn(x: i32, y: i32, f: i32, i: i32, d: i32, e: [u32; 4]) {
    assert_eq!(LatticeBnSampler::new(x, y, f, i).new_domain(d).draw_sample::<4>(), e,
        "latticebn x{x} y{y} f{f} i{i} d{d}");
}
fn ck_pmjbn(x: i32, y: i32, f: i32, i: i32, d: i32, e: [u32; 4]) {
    assert_eq!(PmjBnSampler::new(x, y, f, i).new_domain(d).draw_sample::<4>(), e,
        "pmjbn x{x} y{y} f{f} i{i} d{d}");
}
)RUST");

    // pcg::hash and a sequential pcg::rng stream.
    std::printf("\n#[test]\nfn golden_pcg() {\n");
    for (std::uint32_t k : {0u, 1u, 2u, 7u, 42u, 12345u, 0xffffffffu}) {
        std::printf("    assert_eq!(pcg::hash(0x%08x), 0x%08x);\n", k, oqmc::pcg::hash(k));
    }
    for (std::uint32_t seed : {0u, 1u, 0xdeadbeefu}) {
        std::uint32_t st = seed;
        std::printf("    {\n        let mut st: u32 = 0x%08x;\n", seed);
        for (int i = 0; i < 6; ++i) {
            std::printf("        assert_eq!(pcg::rng(&mut st), 0x%08x);\n", oqmc::pcg::rng(st));
        }
        std::printf("    }\n");
    }
    std::printf("}\n");

    // shuffledScrambledSobol / shuffledRotatedLattice cores.
    std::printf("\n#[test]\nfn golden_cores() {\n");
    for (std::uint32_t seedKey : {0u, 1u, 5u, 99u}) {
        const auto seed = oqmc::pcg::hash(seedKey);
        for (std::uint32_t index : {0u, 1u, 2u, 3u, 255u, 4096u, 65535u}) {
            std::uint32_t o[4];
            oqmc::shuffledScrambledSobol<4>(index, seed, o);
            std::printf("    assert_eq!(owen::shuffled_scrambled_sobol::<4>(%u, 0x%08x), "
                        "[0x%08x, 0x%08x, 0x%08x, 0x%08x]);\n",
                        index, seed, o[0], o[1], o[2], o[3]);
            oqmc::shuffledRotatedLattice<4>(index, seed, o);
            std::printf("    assert_eq!(rank1::shuffled_rotated_lattice::<4>(%u, 0x%08x), "
                        "[0x%08x, 0x%08x, 0x%08x, 0x%08x]);\n",
                        index, seed, o[0], o[1], o[2], o[3]);
        }
    }
    std::printf("}\n");

    // State64Bit field values (raw + decorrelated).
    std::printf("\n#[test]\nfn golden_state() {\n");
    for (auto k : {Case{5, 7, 2, 3, 0}, Case{200, 100, 1, 65536, 0}, Case{256, 3, 0, 70000, 0}}) {
        const oqmc::State64Bit s(k.x, k.y, k.frame, k.index);
        const auto dec = s.pixelDecorrelate();
        std::printf("    {\n        let s = State64Bit::new(%d, %d, %d, %d);\n",
                    k.x, k.y, k.frame, k.index);
        std::printf("        assert_eq!((s.pattern_id, s.sample_id, s.pixel_id), "
                    "(0x%08x, %u, %u));\n", s.patternId, s.sampleId, s.pixelId);
        std::printf("        let d = s.pixel_decorrelate();\n");
        std::printf("        assert_eq!((d.pattern_id, d.sample_id, d.pixel_id), "
                    "(0x%08x, %u, %u));\n", dec.patternId, dec.sampleId, dec.pixelId);
        std::printf("    }\n");
    }
    std::printf("}\n");

    // PMJ init table (a handful of entries from the full 2^16 build).
    std::printf("\n#[test]\nfn golden_pmj_table() {\n");
    {
        constexpr int N = 1 << 16;
        auto table = new std::uint32_t[N][4];
        oqmc::stochasticPmjInit(N, table);
        std::printf("    let mut t = vec![[0u32; 4]; 1 << 16];\n");
        std::printf("    stochastic::stochastic_pmj_init(1 << 16, &mut t);\n");
        for (int i : {0, 1, 2, 100, 1000, 40000, 65535}) {
            std::printf("    assert_eq!(t[%d], [0x%08x, 0x%08x, 0x%08x, 0x%08x]);\n",
                        i, table[i][0], table[i][1], table[i][2], table[i][3]);
        }
        delete[] table;
    }
    std::printf("}\n");

    // Full sampler draws.
    std::printf("\n#[test]\nfn golden_sobol() {\n");
    emitSampler<oqmc::SobolSampler>("ck_sobol", nullptr);
    std::printf("}\n");

    std::printf("\n#[test]\nfn golden_lattice() {\n");
    emitSampler<oqmc::LatticeSampler>("ck_lattice", nullptr);
    std::printf("}\n");

    {
        auto* cache = new char[oqmc::PmjSampler::cacheSize];
        oqmc::PmjSampler::initialiseCache(cache);
        std::printf("\n#[test]\nfn golden_pmj() {\n");
        emitSampler<oqmc::PmjSampler>("ck_pmj", cache);
        std::printf("}\n");
        delete[] cache;
    }
    {
        auto* cache = new char[oqmc::SobolBnSampler::cacheSize];
        oqmc::SobolBnSampler::initialiseCache(cache);
        std::printf("\n#[test]\nfn golden_sobolbn() {\n");
        emitSampler<oqmc::SobolBnSampler>("ck_sobolbn", cache);
        std::printf("}\n");
        delete[] cache;
    }
    {
        auto* cache = new char[oqmc::LatticeBnSampler::cacheSize];
        oqmc::LatticeBnSampler::initialiseCache(cache);
        std::printf("\n#[test]\nfn golden_latticebn() {\n");
        emitSampler<oqmc::LatticeBnSampler>("ck_latticebn", cache);
        std::printf("}\n");
        delete[] cache;
    }
    {
        auto* cache = new char[oqmc::PmjBnSampler::cacheSize];
        oqmc::PmjBnSampler::initialiseCache(cache);
        std::printf("\n#[test]\nfn golden_pmjbn() {\n");
        emitSampler<oqmc::PmjBnSampler>("ck_pmjbn", cache);
        std::printf("}\n");
        delete[] cache;
    }

    return 0;
}
